function ee_kin = forward_kin(l1,l2,theta1,theta2)
%FORWARD_KIN
%    EE_KIN = FORWARD_KIN(L1,L2,THETA1,THETA2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    10-Jan-2017 14:06:37

t2 = theta1+theta2;
ee_kin = [l2.*cos(t2)+l1.*cos(theta1);l2.*sin(t2)+l1.*sin(theta1);0.0];
