function tau_eqn = open_loop_control(theta2,dtheta1,dtheta2,ddtheta1,ddtheta2,l1,l2,m1,m2,d2)
%OPEN_LOOP_CONTROL
%    TAU_EQN = OPEN_LOOP_CONTROL(D2,DDTHETA1,DDTHETA2,DTHETA1,DTHETA2,L1,L2,M1,M2,THETA2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    10-Jan-2017 14:06:38

t2 = l2.^2;
t3 = m2.*t2;
t4 = cos(theta2);
t5 = sin(theta2);
t6 = l1.*l2.*m2.*t4;
t7 = t3+t6;
tau_eqn = [ddtheta1.*(t3+l1.^2.*(m1+m2)+l1.*l2.*m2.*t4.*2.0)+ddtheta2.*t7-d2.*dtheta2.*l1.*m2.*t5.*(dtheta1+dtheta2)+d2.*dtheta1.*dtheta2.*l1.*m2.*t5;ddtheta1.*t7+ddtheta2.*m2.*t2+d2.*dtheta1.^2.*l1.*m2.*t5];
