function P = ForwardKin(L1,L2,th1,th2)
%FORWARDKIN
%    P = FORWARDKIN(L1,L2,TH1,TH2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    22-May-2022 01:06:28

t2 = th1+th2;
P = [-L2.*sin(t2)-L1.*sin(th1);L2.*cos(t2)+L1.*cos(th1);0.0];
