function eqn2 = Thdotdot2(Fdx,Fdy,I1,I2,T1,T2,d1,d2,g,l1,l2,m1,m2,th1,th2,thdot1,thdot2)
%THDOTDOT2
%    EQN2 = THDOTDOT2(FDX,FDY,I1,I2,T1,T2,D1,D2,G,L1,L2,M1,M2,TH1,TH2,THDOT1,THDOT2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    23-Apr-2022 14:18:51

t2 = cos(th2);
t3 = sin(th1);
t4 = sin(th2);
t5 = th1+th2;
t6 = d1.^2;
t7 = d2.^2;
t8 = l1.^2;
t9 = cos(t5);
t10 = sin(t5);
t11 = m1.*t6;
t12 = m2.*t7;
t13 = m2.*t8;
t14 = d2.*l1.*m2.*t2;
t15 = I2+t12;
t16 = t14.*2.0;
t17 = d2.*g.*m2.*t10;
t18 = 1.0./t15;
t19 = t14+t15;
t20 = I1+t11+t13+t15+t16;
t21 = 1.0./t20;
eqn2 = (t18.*(-T2-t17+Fdx.*l2.*t9+Fdy.*l2.*t10+t19.*t21.*(T1+t17-Fdy.*(l1.*t3+l2.*t10)-Fdx.*(l2.*t9+l1.*cos(th1))+g.*t3.*(d1.*m1+l1.*m2)+d2.*l1.*m2.*t4.*thdot2.^2+d2.*l1.*m2.*t4.*thdot1.*thdot2.*2.0)+d2.*l1.*m2.*t4.*thdot1.^2))./(t18.*t19.^2.*t21-1.0);
