function T2Eq = GravityCompT2(d2,g,l1,m2,th1,th2,thdot1)
%GRAVITYCOMPT2
%    T2EQ = GRAVITYCOMPT2(D2,G,L1,M2,TH1,TH2,THDOT1)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    24-Apr-2022 15:13:10

T2Eq = -d2.*m2.*(g.*sin(th1+th2)-l1.*thdot1.^2.*sin(th2));
