function T1Eq = GravityCompT1(d1,d2,g,l1,m1,m2,th1,th2,thdot1,thdot2)
%GRAVITYCOMPT1
%    T1EQ = GRAVITYCOMPT1(D1,D2,G,L1,M1,M2,TH1,TH2,THDOT1,THDOT2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    24-Apr-2022 15:13:10

t2 = sin(th1);
t3 = sin(th2);
T1Eq = -d1.*g.*m1.*t2-g.*l1.*m2.*t2-d2.*g.*m2.*sin(th1+th2)-d2.*l1.*m2.*t3.*thdot2.^2-d2.*l1.*m2.*t3.*thdot1.*thdot2.*2.0;
