function eqn2 = Thdotdot2(I1,I2,T1,T2,d1,d2,g,l1,m1,m2,th1,th2,thdot1,thdot2)
%THDOTDOT2
%    EQN2 = THDOTDOT2(I1,I2,T1,T2,D1,D2,G,L1,M1,M2,TH1,TH2,THDOT1,THDOT2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    24-Apr-2022 15:13:08

t2 = cos(th2);
t3 = sin(th2);
t4 = th1+th2;
t5 = d1.^2;
t6 = d2.^2;
t7 = l1.^2;
t8 = sin(t4);
t9 = m1.*t5;
t10 = m2.*t6;
t11 = m2.*t7;
t12 = d2.*l1.*m2.*t2;
t13 = I2+t10;
t14 = t12.*2.0;
t15 = d2.*g.*m2.*t8;
t16 = 1.0./t13;
t17 = t12+t13;
t18 = I1+t9+t11+t13+t14;
t19 = 1.0./t18;
eqn2 = -(t16.*(T2+t15-t17.*t19.*(T1+t15+g.*sin(th1).*(d1.*m1+l1.*m2)+d2.*l1.*m2.*t3.*thdot2.^2+d2.*l1.*m2.*t3.*thdot1.*thdot2.*2.0)-d2.*l1.*m2.*t3.*thdot1.^2))./(t16.*t17.^2.*t19-1.0);
