function tau1Eq = grav_comp_tau1(Fdx,Fdy,d1,d2,dtheta1,dtheta2,g,l1,l2,m1,m2,theta1,theta2)
%GRAV_COMP_TAU1
%    TAU1EQ = GRAV_COMP_TAU1(FDX,FDY,D1,D2,DTHETA1,DTHETA2,G,L1,L2,M1,M2,THETA1,THETA2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    29-Nov-2016 15:30:00

t2 = theta1+theta2;
t3 = cos(t2);
t4 = cos(theta1);
t5 = sin(theta2);
tau1Eq = -Fdy.*l1.*t4-Fdy.*l2.*t3+Fdx.*l2.*sin(t2)+Fdx.*l1.*sin(theta1)+d1.*g.*m1.*t4+d2.*g.*m2.*t3+g.*l1.*m2.*t4-d2.*dtheta2.^2.*l1.*m2.*t5-d2.*dtheta1.*dtheta2.*l1.*m2.*t5.*2.0;
