function T1Eq = GravityCompT1(Fdx,L1,L2,g,m1,m2,th1,th2,thdot1,thdot2)
%GRAVITYCOMPT1
%    T1EQ = GRAVITYCOMPT1(FDX,L1,L2,G,M1,M2,TH1,TH2,THDOT1,THDOT2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    19-Apr-2022 14:42:43

t2 = sin(th1);
t3 = sin(th2);
t4 = th1+th2;
t5 = sin(t4);
T1Eq = Fdx.*L1.*t2+Fdx.*L2.*t5+L1.*g.*m1.*t2+L1.*g.*m2.*t2+L2.*g.*m2.*t5+L1.*L2.*m2.*t3.*thdot2.^2+L1.*L2.*m2.*t3.*thdot1.*thdot2.*2.0;
