function T2Eq = GravityCompT2(Fdy,L1,L2,g,m2,th1,th2,thdot1,thdot2)
%GRAVITYCOMPT2
%    T2EQ = GRAVITYCOMPT2(FDY,L1,L2,G,M2,TH1,TH2,THDOT1,THDOT2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    19-Apr-2022 14:42:43

t2 = th1+th2;
T2Eq = Fdy.*L2.*cos(t2)+Fdy.*L1.*cos(th1)+L2.*g.*m2.*sin(t2)+L1.*L2.*m2.*thdot1.*thdot2.*sin(th2);
