function Imp = ImpedenceControl(Kd,Kp,L1,L2,desiredP,desiredPdot,th1,th2,thdot1,thdot2)
%IMPEDENCECONTROL
%    IMP = IMPEDENCECONTROL(KD,KP,L1,L2,DESIREDP,DESIREDPDOT,TH1,TH2,THDOT1,THDOT2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    19-Apr-2022 14:42:43

t2 = cos(th1);
t3 = sin(th1);
t4 = th1+th2;
t5 = L1.*t2;
t6 = L1.*t3;
t7 = cos(t4);
t8 = sin(t4);
t9 = L2.*t7;
t10 = L2.*t8;
Imp = [Kp.*(desiredP+t6+t10)+Kd.*(desiredPdot+thdot1.*(t6+t10)+t10.*thdot2);-Kd.*(-desiredPdot+thdot1.*(t5+t9)+t9.*thdot2)-Kp.*(-desiredP+t5+t9);Kd.*desiredPdot+Kp.*desiredP];
