function EQthdotdot2 = Thdotdot2(Fdx,Fdy,L1,L2,T1,T2,g,m1,m2,th1,th2,thdot1,thdot2)
%THDOTDOT2
%    EQTHDOTDOT2 = THDOTDOT2(FDX,FDY,L1,L2,T1,T2,G,M1,M2,TH1,TH2,THDOT1,THDOT2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    19-Apr-2022 14:42:42

t2 = cos(th2);
t3 = sin(th1);
t4 = sin(th2);
t5 = th1+th2;
t6 = L1.^2;
t7 = L2.^2;
t8 = sin(t5);
t9 = m1.*t6;
t10 = m2.*t6;
t11 = m2.*t7;
t12 = L1.*L2.*m2.*t2.*2.0;
t13 = L2.*g.*m2.*t8;
t14 = t9+t10+t11+t12;
EQthdotdot2 = (t14.*(-T2+t13+Fdy.*(L2.*cos(t5)+L1.*cos(th1))-(L2.*m2.*(L2+L1.*t2).*(-T1+t13+Fdx.*(L1.*t3+L2.*t8)+L1.*g.*t3.*(m1+m2)+L1.*L2.*m2.*t4.*thdot2.*(thdot1.*2.0+thdot2)))./t14+L1.*L2.*m2.*t4.*thdot1.*thdot2))./(t7.*t10.*(m1+m2-m2.*t2.^2));
