function eqn1 = Thdotdot1(Fdx,Fdy,I1,I2,T1,T2,d1,d2,g,l1,l2,m1,m2,th1,th2,thdot1,thdot2)
%THDOTDOT1
%    EQN1 = THDOTDOT1(FDX,FDY,I1,I2,T1,T2,D1,D2,G,L1,L2,M1,M2,TH1,TH2,THDOT1,THDOT2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    10-Mar-2022 14:33:48

t2 = cos(th1);
t3 = sin(th1);
t4 = sin(th2);
t5 = d1.^2;
t6 = d2.^2;
t7 = d2.^3;
t8 = l1.^2;
t9 = m2.^2;
t10 = th2.*2.0;
t11 = thdot1.^2;
t12 = thdot2.^2;
t13 = t10+th1;
t14 = sin(t13);
et1 = 1.0./(I1.*I2.*2.0+I2.*m1.*t5.*2.0+I1.*m2.*t6.*2.0+I2.*m2.*t8.*2.0+t6.*t8.*t9+m1.*m2.*t5.*t6.*2.0-t6.*t8.*t9.*cos(t10));
et2 = I2.*T1.*2.0-I2.*T2.*2.0+T1.*m2.*t6.*2.0-T2.*m2.*t6.*2.0-Fdx.*I2.*l1.*t2.*2.0-Fdy.*I2.*l1.*t3.*2.0+t6.*t8.*t9.*t11.*sin(t10)+I2.*d1.*g.*m1.*t3.*2.0+I2.*g.*l1.*m2.*t3.*2.0-Fdx.*l1.*m2.*t2.*t6.*2.0-Fdy.*l1.*m2.*t3.*t6.*2.0+g.*l1.*t3.*t6.*t9-g.*l1.*t6.*t9.*t14+l1.*t4.*t7.*t9.*t11.*2.0+l1.*t4.*t7.*t9.*t12.*2.0-T2.*d2.*l1.*m2.*cos(th2).*2.0+l1.*t4.*t7.*t9.*thdot1.*thdot2.*4.0+Fdx.*d2.*l1.*l2.*m2.*cos(t13)+Fdx.*d2.*l1.*l2.*m2.*t2+Fdy.*d2.*l1.*l2.*m2.*t3+Fdy.*d2.*l1.*l2.*m2.*t14+I2.*d2.*l1.*m2.*t4.*t11.*2.0+I2.*d2.*l1.*m2.*t4.*t12.*2.0+d1.*g.*m1.*m2.*t3.*t6.*2.0+I2.*d2.*l1.*m2.*t4.*thdot1.*thdot2.*4.0;
eqn1 = et1.*et2;
