function eqn2 = Thdotdot2(Fdx,Fdy,I1,I2,T1,T2,d1,d2,g,l1,l2,m1,m2,th1,th2,thdot1,thdot2)
%THDOTDOT2
%    EQN2 = THDOTDOT2(FDX,FDY,I1,I2,T1,T2,D1,D2,G,L1,L2,M1,M2,TH1,TH2,THDOT1,THDOT2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    10-Mar-2022 14:33:48

t2 = cos(th1);
t3 = cos(th2);
t4 = sin(th1);
t5 = sin(th2);
t6 = th1+th2;
t7 = d1.^2;
t8 = d2.^2;
t9 = d2.^3;
t10 = l1.^2;
t11 = m2.^2;
t12 = th2.*2.0;
t13 = thdot1.^2;
t14 = thdot2.^2;
t18 = -th2;
t15 = sin(t12);
t16 = cos(t6);
t17 = sin(t6);
t19 = t6+th2;
t21 = t18+th1;
t20 = sin(t19);
t22 = sin(t21);
et1 = I1.*T2.*-2.0+I2.*T1.*2.0-I2.*T2.*2.0-T2.*m1.*t7.*2.0+T1.*m2.*t8.*2.0-T2.*m2.*t8.*2.0-T2.*m2.*t10.*2.0-Fdx.*I2.*l1.*t2.*2.0+Fdx.*I1.*l2.*t16.*2.0-Fdy.*I2.*l1.*t4.*2.0+Fdy.*I1.*l2.*t17.*2.0+I2.*d1.*g.*m1.*t4.*2.0-I1.*d2.*g.*m2.*t17.*2.0+I2.*g.*l1.*m2.*t4.*2.0-Fdx.*d2.*m2.*t10.*t16-Fdy.*d2.*m2.*t10.*t17-Fdy.*d2.*m2.*t10.*t22+T1.*d2.*l1.*m2.*t3.*2.0-T2.*d2.*l1.*m2.*t3.*4.0-Fdx.*l1.*m2.*t2.*t8.*2.0+Fdx.*l2.*m1.*t7.*t16.*2.0+Fdx.*l2.*m2.*t10.*t16.*2.0-Fdy.*l1.*m2.*t4.*t8.*2.0+Fdy.*l2.*m1.*t7.*t17.*2.0+Fdy.*l2.*m2.*t10.*t17.*2.0-d2.*g.*t10.*t11.*t17+d2.*g.*t10.*t11.*t22+g.*l1.*t4.*t8.*t11-g.*l1.*t8.*t11.*t20;
et2 = l1.*t5.*t9.*t11.*t13.*2.0+l1.*t5.*t9.*t11.*t14.*2.0+t8.*t10.*t11.*t13.*t15.*2.0+t8.*t10.*t11.*t14.*t15-Fdx.*d2.*m2.*t10.*cos(t21)+d2.*l1.^3.*t5.*t11.*t13.*2.0+l1.*t5.*t9.*t11.*thdot1.*thdot2.*4.0+t8.*t10.*t11.*t15.*thdot1.*thdot2.*2.0+Fdx.*d2.*l1.*l2.*m2.*cos(t19)+Fdx.*d2.*l1.*l2.*m2.*t2+Fdy.*d2.*l1.*l2.*m2.*t4+Fdy.*d2.*l1.*l2.*m2.*t20+I1.*d2.*l1.*m2.*t5.*t13.*2.0+I2.*d2.*l1.*m2.*t5.*t13.*2.0+I2.*d2.*l1.*m2.*t5.*t14.*2.0+d1.*g.*m1.*m2.*t4.*t8.*2.0-d2.*g.*m1.*m2.*t7.*t17.*2.0+I2.*d2.*l1.*m2.*t5.*thdot1.*thdot2.*4.0+d1.*d2.*g.*l1.*m1.*m2.*t17+d1.*d2.*g.*l1.*m1.*m2.*t22+d2.*l1.*m1.*m2.*t5.*t7.*t13.*2.0;
eqn2 = -(et1+et2)./(I1.*I2.*2.0+I2.*m1.*t7.*2.0+I1.*m2.*t8.*2.0+I2.*m2.*t10.*2.0+t8.*t10.*t11+m1.*m2.*t7.*t8.*2.0-t8.*t10.*t11.*cos(t12));
