function Ta = MyImpedenceControl(Kd,Kp,l1,l2,th1,th2,thdot1,thdot2,xdott,xt,ydott,yt)
%MYIMPEDENCECONTROL
%    TA = MYIMPEDENCECONTROL(KD,KP,L1,L2,TH1,TH2,THDOT1,THDOT2,XDOTT,XT,YDOTT,YT)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    12-Mar-2022 00:37:39

t2 = cos(th1);
t3 = cos(th2);
t4 = sin(th1);
t5 = sin(th2);
t6 = th1+th2;
t7 = l1.*t2;
t8 = l2.*t3;
t9 = cos(t6);
t10 = l1.*t4;
t11 = l2.*t5;
t12 = sin(t6);
t13 = l2.*t9;
t14 = l2.*t12;
t17 = t7+t8+xt;
t18 = t10+t11+yt;
t15 = t13.*thdot2;
t16 = t14.*thdot2;
t19 = t7+t13;
t20 = t10+t14;
t21 = Kp.*t17;
t22 = Kp.*t18;
t23 = t19.*thdot1;
t24 = t20.*thdot1;
t25 = t15+t23+xdott;
t26 = t16+t24+ydott;
t27 = Kd.*t25;
t28 = Kd.*t26;
t29 = t22+t28;
t30 = t21+t27;
Ta = [-t19.*t30-t20.*t29;-t13.*t30-t14.*t29];
