function eqn2 = MyThdotdot2(Fdx,Fdy,I1,I2,T1,g,l1,l2,m1,m2,th1,th2,thdot1,thdot2)
%MYTHDOTDOT2
%    EQN2 = MYTHDOTDOT2(FDX,FDY,I1,I2,T1,G,L1,L2,M1,M2,TH1,TH2,THDOT1,THDOT2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    12-Mar-2022 00:37:38

t2 = cos(th1);
t3 = cos(th2);
t4 = sin(th2);
t5 = I1+I2;
t7 = -th2;
t6 = l1.*t3;
t8 = 1.0./t5;
t10 = t7+th1;
t9 = l2+t6;
t11 = sin(t10);
eqn2 = (1.0./l2.^2.*(-Fdy+g.*l2.*m2.*cos(th1+th2)+l2.*m2.*t8.*t9.*(T1+Fdx.*l2.*t4-Fdy.*l1.*t2-Fdy.*l2.*t3+Fdx.*l1.*sin(th1)+(g.*l1.*m1.*t2)./2.0+g.*l1.*m2.*t2+(g.*l2.*m2.*t3)./2.0-(l1.*l2.*m2.*t11.*thdot2.^2)./2.0-l1.*l2.*m2.*t11.*thdot1.*thdot2)+l1.*l2.*m2.*t4.*thdot1.^2))./(m2.*((t8.*t9.*(I2-(l1.*l2.*m2.*t11)./2.0))./l2-1.0));
